### ISSUE TITLE
Add option to add classpath

### ISSUE THREAD

**Issue by pfeodrippe** [tangruize/tlc-cmd#2]
Is there any way that we can add to the classpath of the running JVM? If so, it would be composable with tools like https://github.com/pfeodrippe/tladeps (using `--tladeps-classpath`), leveraging modules already built.

And great tool BTW =) More people will be able to use and learn about TLA+ because of people like you.

**Comment by tangruize** [comment]
Thank you! It is a good feature. I will add an option to support it.

**Comment by tangruize** [comment]
Added a new "-j CLASSPATH" option. It works well with tladeps!

**Comment by pfeodrippe** [comment]
Thank you :D
